### PR TITLE
connectModules rewritten to use connectAdvanced

### LINKED ISSUE #117: Connect has been rewritten to not use setState
https://github.com/reactjs/react-redux/pull/416

should we use react-redux's connect?

### PR DESCRIPTION
**Pull request by mboperator**
## Changes
- Ripped out old `connect` code and moved to using `connectAdvanced` 
- Added `react-redux` as a peer dependency

## Discussion
- Thinking of removing the ability to pass `dispatch` as a prop to override store dispatch

Closes #117

### CODE REVIEW

**Comment by michaelghinrichs** [comment]
what does `connect-advanced` do?

**Comment by michaelghinrichs** [comment]
Also, the issue that we just resolved for 0.6.7, is there a way of doing something similar here?

**Comment by mboperator** [comment]
@michaelghinrichs We opted to use `connect-advanced` for two major reasons:
1) Maintainability
2) Performance

We originally copy-pasted `connect` in to create `connectModules` a while back. Upsides were a decreased bundle size and no reliance on `react-redux`, downside was that we didn't get any updates going forward.

Moving to adding `react-redux` as a peer dependency and using `connectAdvanced` allows us to stay up to date with the latest and greatest, and we also have a clean interface to using `connect`'s internals without copying all of their code.

Also, connect advanced is much (10x) faster than what we had.

**Comment by mboperator** [comment]
@michaelghinrichs Almost! This means the component's `displayName` property will be calculated by connectAdvanced, and we can override it too. 

It'll look like `connectAdvanced(ComponentName)`.

**Pull request merged**
