### PR TITLE
Remove propCheck middleware from package

### LINKED ISSUE #94: Move `propCheck` to own package.
It's not really to use `redux-modules`.  It's just middleware.

### PR DESCRIPTION
**Pull request by mboperator**
# Description
This removes the `propCheck` middleware from the `redux-modules` package. This middleware and others can now be found in [redux-modules-middleware](https://github.com/mboperator/redux-modules-middleware)

Closes #94 

## This is a **breaking** change ⚠️

### CODE REVIEW

**Comment by brock-noah** [comment]
It has to be done eventually as applying middleware has changed and `redux-modules-middleware` is the new route. 👍 
Maybe a 2.0.0 issue, maybe a branch, to track/time things?

**Comment by wtgtybhertgeghgtwtg** [comment]
Why does this make `invariant` a `peerDependency`?

**Comment by wtgtybhertgeghgtwtg** [comment]
More to the point, yes, this would be breaking.  You could just proxy the feature for now and add a deprecation warning, or you could bump to `redux-modules@2.0.0`.  If you are going to bump to the next major version, I would like the other pending breaking changes (#100 and #109) to be accepted or denied before publishing, so there won't have to be another major bump just for those.

**Comment by mboperator** [comment]
This adds `invariant` as the mechanism with which I'm including the deprecation warning. I wasn't sure about that move so I'm glad to start the discussion here. I had it listed as a `peerDependency` because `react` requires it as a dependency.

I'm open to skipping the warning altogether, and moving straight to `v2.0.0` while solving the issues you've mentioned, though I'd like to get more opinions since `Procore` uses the selector key pretty heavily.

**Comment by wtgtybhertgeghgtwtg** [comment]
`invariant` should not be a `peerDependency`.  Just set it as a `dependency` with a version string that's compatible with the one `react` uses and it'll dedupe.

**Pull request merged**
